### ISSUE TITLE
Reexports from CTDirect

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#176]
@PierreMartinon shouldn't we reexport `OCPInit` (and maybe some other things) from CTDirect.jl?

**Comment by PierreMartinon** [comment]
Hi there. To clarify on the current state of the initialization:
- *OCPInit* is the one creating the generic initialization structure (ie. functions) and is in CTBase. It should be reexported from CTDirect, I'll need to check. This method call has been made optional in most cases, passing directly the arguments e.g. *init=sol* instead of *init=OCPInit(sol)*. Ideally at some point it will become a purely internal function ?
- *DOCP_initial_guess* takes such an OCPInit and builds the (vector) initial guess for the discretized problem. It is currently nor exported since it is not normally called by the user: the init is rather passed to *solve()*, or *directTranscription()* / *setDOCPInit()* if you want to interact with the NLP problem directly.

**Comment by ocots** [comment]
I have the same question about being purely internal in another package and I don't have the answer.

**Comment by PierreMartinon** [comment]
I just checked, CTBase.OCPInit() is exported in CTDirect.

**Comment by jbcaillau** [comment]
> @PierreMartinon shouldn't we reexport `OCPInit` (and maybe some other things) from CTDirect.jl?

So, @PierreMartinon, yes or no?

**Comment by PierreMartinon** [comment]
> I just checked, CTBase.OCPInit() is exported in CTDirect.

o_O

**Comment by ocots** [comment]
It is `OptimalControlInit` now, no?

**Comment by PierreMartinon** [comment]
Yup
